using System.Text;
using FastJson.Generator.Models;

namespace FastJson.Generator;

/// <summary>
/// Generates AOT-compatible source code for FastJson serialization.
/// Creates JsonTypeInfo implementations using System.Text.Json metadata APIs.
/// Optimized for performance with direct JsonTypeInfo access.
/// </summary>
public static class CodeEmitter
{
    /// <summary>
    /// Emits the FastJsonContext.g.cs file containing all serialization infrastructure.
    /// </summary>
    public static string EmitContext(EquatableArray<TypeModel> types, FastJsonOptionsModel options)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type");
        sb.AppendLine("#pragma warning disable CS8601 // Possible null reference assignment");
        sb.AppendLine("#pragma warning disable CS8602 // Dereference of a possibly null reference");
        sb.AppendLine("#pragma warning disable CS8603 // Possible null reference return");
        sb.AppendLine("#pragma warning disable CS8604 // Possible null reference argument");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace FastJson;");
        sb.AppendLine();

        // Emit custom TypeInfoResolver first (needs to be before FastJsonContext for forward reference)
        EmitTypeInfoResolver(sb, types);
        sb.AppendLine();

        // Emit main context class with cached JsonTypeInfo properties
        sb.AppendLine("internal static class FastJsonContext");
        sb.AppendLine("{");

        // Emit static options (used for creating JsonTypeInfo)
        EmitOptionsCreation(sb, options);
        sb.AppendLine();

        // Emit cached JsonTypeInfo<T> properties for each type
        foreach (var type in types)
        {
            sb.AppendLine($"    private static JsonTypeInfo<{type.FullyQualifiedName}>? _{type.ContextPropertyName};");
            sb.AppendLine($"    public static JsonTypeInfo<{type.FullyQualifiedName}> {type.ContextPropertyName} => _{type.ContextPropertyName} ??= Create_{type.ContextPropertyName}();");
            sb.AppendLine();
        }

        // Emit Create methods for each type
        foreach (var type in types)
        {
            EmitCreateTypeInfo(sb, type, options);
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // Emit module initializer
        EmitModuleInitializer(sb, types);

        return sb.ToString();
    }

    private static void EmitOptionsCreation(StringBuilder sb, FastJsonOptionsModel options)
    {
        sb.AppendLine("    private static readonly JsonSerializerOptions _options = CreateOptions();");
        sb.AppendLine();
        sb.AppendLine("    private static JsonSerializerOptions CreateOptions()");
        sb.AppendLine("    {");
        sb.AppendLine("        var options = new JsonSerializerOptions");
        sb.AppendLine("        {");
        sb.AppendLine($"            PropertyNamingPolicy = {GetNamingPolicyCode(options.PropertyNamingPolicy)},");
        sb.AppendLine($"            WriteIndented = {options.WriteIndented.ToString().ToLower()},");
        sb.AppendLine($"            PropertyNameCaseInsensitive = {options.PropertyNameCaseInsensitive.ToString().ToLower()},");
        sb.AppendLine($"            AllowTrailingCommas = {options.AllowTrailingCommas.ToString().ToLower()},");
        sb.AppendLine("            IncludeFields = true,");
        if (options.DefaultIgnoreCondition)
        {
            sb.AppendLine("            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,");
        }
        if (options.ReadCommentHandling)
        {
            sb.AppendLine("            ReadCommentHandling = JsonCommentHandling.Skip,");
        }
        sb.AppendLine("            TypeInfoResolver = JsonTypeInfoResolver.Combine(FastJsonTypeInfoResolver.Instance, new DefaultJsonTypeInfoResolver())");
        sb.AppendLine("        };");
        sb.AppendLine("        return options;");
        sb.AppendLine("    }");
    }

    private static void EmitTypeInfoResolver(StringBuilder sb, EquatableArray<TypeModel> types)
    {
        sb.AppendLine("internal sealed class FastJsonTypeInfoResolver : IJsonTypeInfoResolver");
        sb.AppendLine("{");
        sb.AppendLine("    public static FastJsonTypeInfoResolver Instance { get; } = new();");
        sb.AppendLine();
        sb.AppendLine("    public JsonTypeInfo? GetTypeInfo(Type type, JsonSerializerOptions options)");
        sb.AppendLine("    {");

        foreach (var type in types)
        {
            sb.AppendLine($"        if (type == typeof({type.FullyQualifiedName}))");
            sb.AppendLine($"            return FastJsonContext.{type.ContextPropertyName};");
        }

        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitModuleInitializer(StringBuilder sb, EquatableArray<TypeModel> types)
    {
        sb.AppendLine("internal static class FastJsonInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        FastJson.Configure(SerializeImpl, DeserializeImpl, SerializeAsyncImpl, DeserializeAsyncImpl);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Emit SerializeImpl - using direct JsonTypeInfo
        EmitSerializeImpl(sb, types);
        sb.AppendLine();

        // Emit DeserializeImpl - using direct JsonTypeInfo
        EmitDeserializeImpl(sb, types);
        sb.AppendLine();

        // Emit SerializeAsyncImpl
        EmitSerializeAsyncImpl(sb, types);
        sb.AppendLine();

        // Emit DeserializeAsyncImpl
        EmitDeserializeAsyncImpl(sb, types);

        sb.AppendLine("}");
    }

    private static void EmitSerializeImpl(StringBuilder sb, EquatableArray<TypeModel> types)
    {
        sb.AppendLine("    private static string SerializeImpl(object? value, Type type)");
        sb.AppendLine("    {");

        foreach (var type in types)
        {
            sb.AppendLine($"        if (type == typeof({type.FullyQualifiedName}))");
            sb.AppendLine($"            return JsonSerializer.Serialize(({type.FullyQualifiedName})value!, FastJsonContext.{type.ContextPropertyName});");
            sb.AppendLine();
        }

        sb.AppendLine("        throw new InvalidOperationException($\"Type {type} is not registered for FastJson serialization. Add [assembly: FastJsonInclude(typeof({type}))] to register it.\");");
        sb.AppendLine("    }");
    }

    private static void EmitDeserializeImpl(StringBuilder sb, EquatableArray<TypeModel> types)
    {
        sb.AppendLine("    private static object? DeserializeImpl(string json, Type type)");
        sb.AppendLine("    {");

        foreach (var type in types)
        {
            sb.AppendLine($"        if (type == typeof({type.FullyQualifiedName}))");
            sb.AppendLine($"            return JsonSerializer.Deserialize(json, FastJsonContext.{type.ContextPropertyName});");
            sb.AppendLine();
        }

        sb.AppendLine("        throw new InvalidOperationException($\"Type {type} is not registered for FastJson deserialization. Add [assembly: FastJsonInclude(typeof({type}))] to register it.\");");
        sb.AppendLine("    }");
    }

    private static void EmitSerializeAsyncImpl(StringBuilder sb, EquatableArray<TypeModel> types)
    {
        sb.AppendLine("    private static Task SerializeAsyncImpl(Stream stream, object? value, Type type, CancellationToken cancellationToken)");
        sb.AppendLine("    {");

        foreach (var type in types)
        {
            sb.AppendLine($"        if (type == typeof({type.FullyQualifiedName}))");
            sb.AppendLine($"            return JsonSerializer.SerializeAsync(stream, ({type.FullyQualifiedName})value!, FastJsonContext.{type.ContextPropertyName}, cancellationToken);");
            sb.AppendLine();
        }

        sb.AppendLine("        throw new InvalidOperationException($\"Type {type} is not registered for FastJson serialization. Add [assembly: FastJsonInclude(typeof({type}))] to register it.\");");
        sb.AppendLine("    }");
    }

    private static void EmitDeserializeAsyncImpl(StringBuilder sb, EquatableArray<TypeModel> types)
    {
        sb.AppendLine("    private static async ValueTask<object?> DeserializeAsyncImpl(Stream stream, Type type, CancellationToken cancellationToken)");
        sb.AppendLine("    {");

        foreach (var type in types)
        {
            sb.AppendLine($"        if (type == typeof({type.FullyQualifiedName}))");
            sb.AppendLine($"            return await JsonSerializer.DeserializeAsync(stream, FastJsonContext.{type.ContextPropertyName}, cancellationToken).ConfigureAwait(false);");
            sb.AppendLine();
        }

        sb.AppendLine("        throw new InvalidOperationException($\"Type {type} is not registered for FastJson deserialization. Add [assembly: FastJsonInclude(typeof({type}))] to register it.\");");
        sb.AppendLine("    }");
    }

    private static void EmitCreateTypeInfo(StringBuilder sb, TypeModel type, FastJsonOptionsModel options)
    {
        sb.AppendLine($"    private static JsonTypeInfo<{type.FullyQualifiedName}> Create_{type.ContextPropertyName}()");
        sb.AppendLine("    {");

        if (type.ConverterTypeName != null)
        {
            sb.AppendLine($"        return JsonMetadataServices.CreateValueInfo<{type.FullyQualifiedName}>(_options, new {type.ConverterTypeName}());");
            sb.AppendLine("    }");
        }
        else if (type.IsEnum)
        {
            sb.AppendLine($"        return JsonMetadataServices.CreateValueInfo<{type.FullyQualifiedName}>(_options, JsonMetadataServices.GetEnumConverter<{type.FullyQualifiedName}>(_options));");
            sb.AppendLine("    }");
        }
        else if (type.IsCollection)
        {
            EmitCollectionTypeInfo(sb, type);
            sb.AppendLine("    }");
        }
        else
        {
            EmitObjectTypeInfo(sb, type, options);
        }
    }

    private static void EmitCollectionTypeInfo(StringBuilder sb, TypeModel type)
    {
        if (type.KeyTypeName != null && type.ValueTypeName != null)
        {
            // Dictionary type
            sb.AppendLine($"        var info = JsonMetadataServices.CreateDictionaryInfo<{type.FullyQualifiedName}, {type.KeyTypeName}, {type.ValueTypeName}>(");
            sb.AppendLine("            _options,");
            sb.AppendLine($"            new JsonCollectionInfoValues<{type.FullyQualifiedName}>()");
            sb.AppendLine("            {");
            sb.AppendLine($"                ObjectCreator = static () => new {type.FullyQualifiedName}(),");
            sb.AppendLine($"                KeyInfo = (JsonTypeInfo<{type.KeyTypeName}>)_options.GetTypeInfo(typeof({type.KeyTypeName}))!,");
            sb.AppendLine($"                ElementInfo = (JsonTypeInfo<{type.ValueTypeName}>)_options.GetTypeInfo(typeof({type.ValueTypeName}))!");
            sb.AppendLine("            });");
        }
        else if (type.ElementTypeName != null)
        {
            if (type.FullyQualifiedName.EndsWith("[]"))
            {
                // Array
                sb.AppendLine($"        var info = JsonMetadataServices.CreateArrayInfo<{type.ElementTypeName}>(");
                sb.AppendLine("            _options,");
                sb.AppendLine($"            new JsonCollectionInfoValues<{type.ElementTypeName}[]>()");
                sb.AppendLine("            {");
                sb.AppendLine($"                ElementInfo = (JsonTypeInfo<{type.ElementTypeName}>)_options.GetTypeInfo(typeof({type.ElementTypeName}))!");
                sb.AppendLine("            });");
            }
            else
            {
                // List
                sb.AppendLine($"        var info = JsonMetadataServices.CreateListInfo<{type.FullyQualifiedName}, {type.ElementTypeName}>(");
                sb.AppendLine("            _options,");
                sb.AppendLine($"            new JsonCollectionInfoValues<{type.FullyQualifiedName}>()");
                sb.AppendLine("            {");
                sb.AppendLine($"                ObjectCreator = static () => new {type.FullyQualifiedName}(),");
                sb.AppendLine($"                ElementInfo = (JsonTypeInfo<{type.ElementTypeName}>)_options.GetTypeInfo(typeof({type.ElementTypeName}))!");
                sb.AppendLine("            });");
            }
        }
        else
        {
            sb.AppendLine($"        throw new NotSupportedException(\"Collection type {type.FullyQualifiedName} is not supported.\");");
            sb.AppendLine($"        #pragma warning disable CS0162");
            sb.AppendLine($"        return null!;");
            sb.AppendLine($"        #pragma warning restore CS0162");
            return;
        }

        sb.AppendLine("        return info;");
    }

    private static void EmitObjectTypeInfo(StringBuilder sb, TypeModel type, FastJsonOptionsModel options)
    {
        bool useParameterizedCtor = type.ConstructorParameters.Length > 0 && !type.HasParameterlessConstructor;

        sb.AppendLine($"        var info = JsonMetadataServices.CreateObjectInfo<{type.FullyQualifiedName}>(");
        sb.AppendLine("            _options,");
        sb.AppendLine($"            new JsonObjectInfoValues<{type.FullyQualifiedName}>()");
        sb.AppendLine("            {");

        if (type.IsAbstract)
        {
            sb.AppendLine("                ObjectCreator = null,");
        }
        else if (useParameterizedCtor)
        {
            sb.AppendLine("                ObjectCreator = null,");
            sb.AppendLine($"                ObjectWithParameterizedConstructorCreator = static args => Create_{type.ContextPropertyName}_FromArgs(args),");
            sb.AppendLine($"                ConstructorParameterMetadataInitializer = static () => Create_{type.ContextPropertyName}_CtorParams(),");
        }
        else if (type.HasParameterlessConstructor)
        {
            sb.AppendLine($"                ObjectCreator = static () => new {type.FullyQualifiedName}(),");
        }
        else
        {
            sb.AppendLine("                ObjectCreator = null,");
        }

        sb.AppendLine($"                PropertyMetadataInitializer = _ => Create_{type.ContextPropertyName}_Properties(),");
        sb.AppendLine("                SerializeHandler = null");
        sb.AppendLine("            });");

        // Add polymorphism options if needed
        if (type.IsPolymorphic && type.DerivedTypes.Length > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        info.PolymorphismOptions = new JsonPolymorphismOptions");
            sb.AppendLine("        {");
            sb.AppendLine($"            TypeDiscriminatorPropertyName = \"{type.TypeDiscriminatorPropertyName ?? "$type"}\",");
            sb.AppendLine("            IgnoreUnrecognizedTypeDiscriminators = false,");
            sb.AppendLine("            UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FailSerialization");
            sb.AppendLine("        };");

            foreach (var derived in type.DerivedTypes)
            {
                if (derived.TypeDiscriminator != null)
                {
                    if (derived.IsStringDiscriminator)
                    {
                        sb.AppendLine($"        info.PolymorphismOptions.DerivedTypes.Add(new JsonDerivedType(typeof({derived.TypeFullyQualifiedName}), \"{derived.TypeDiscriminator}\"));");
                    }
                    else
                    {
                        sb.AppendLine($"        info.PolymorphismOptions.DerivedTypes.Add(new JsonDerivedType(typeof({derived.TypeFullyQualifiedName}), {derived.TypeDiscriminator}));");
                    }
                }
                else
                {
                    sb.AppendLine($"        info.PolymorphismOptions.DerivedTypes.Add(new JsonDerivedType(typeof({derived.TypeFullyQualifiedName})));");
                }
            }
        }

        sb.AppendLine("        return info;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Emit property metadata method
        EmitPropertyMetadata(sb, type, options);

        // Emit constructor methods if using parameterized constructor
        if (useParameterizedCtor && !type.IsAbstract)
        {
            sb.AppendLine();
            EmitConstructorMethods(sb, type, options);
        }
    }

    private static void EmitPropertyMetadata(StringBuilder sb, TypeModel type, FastJsonOptionsModel options)
    {
        sb.AppendLine($"    private static JsonPropertyInfo[] Create_{type.ContextPropertyName}_Properties()");
        sb.AppendLine("    {");

        var visibleProperties = new System.Collections.Generic.List<PropertyModel>();
        foreach (var p in type.Properties)
        {
            if (!p.IsIgnored)
                visibleProperties.Add(p);
        }

        if (visibleProperties.Count == 0)
        {
            sb.AppendLine("        return Array.Empty<JsonPropertyInfo>();");
        }
        else
        {
            sb.AppendLine($"        var properties = new JsonPropertyInfo[{visibleProperties.Count}];");
            sb.AppendLine();

            var index = 0;
            foreach (var prop in visibleProperties)
            {
                var jsonName = prop.JsonName;

                sb.AppendLine($"        properties[{index}] = JsonMetadataServices.CreatePropertyInfo<{prop.TypeFullyQualifiedName}>(");
                sb.AppendLine("            _options,");
                sb.AppendLine($"            new JsonPropertyInfoValues<{prop.TypeFullyQualifiedName}>()");
                sb.AppendLine("            {");
                sb.AppendLine($"                IsProperty = {(!prop.IsField).ToString().ToLower()},");
                sb.AppendLine($"                IsPublic = {prop.IsPublic.ToString().ToLower()},");
                sb.AppendLine($"                DeclaringType = typeof({type.FullyQualifiedName}),");
                sb.AppendLine($"                PropertyName = \"{prop.Name}\",");
                sb.AppendLine($"                JsonPropertyName = \"{jsonName}\",");

                if (prop.HasGetter)
                {
                    sb.AppendLine($"                Getter = static obj => (({type.FullyQualifiedName})obj).{prop.Name},");
                }
                else
                {
                    sb.AppendLine("                Getter = null,");
                }

                if (prop.HasSetter && !prop.IsInitOnly)
                {
                    sb.AppendLine($"                Setter = static (obj, val) => (({type.FullyQualifiedName})obj).{prop.Name} = val,");
                }
                else
                {
                    sb.AppendLine("                Setter = null,");
                }

                if (prop.IsRequired)
                {
                    sb.AppendLine("                IsRequired = true,");
                }

                if (prop.NumberHandling != null)
                {
                    sb.AppendLine($"                NumberHandling = {prop.NumberHandling},");
                }

                if (prop.ConverterTypeName != null)
                {
                    sb.AppendLine($"                JsonTypeInfo = JsonMetadataServices.CreateValueInfo<{prop.TypeFullyQualifiedName}>(_options, new {prop.ConverterTypeName}()),");
                }

                sb.AppendLine("            });");
                sb.AppendLine();
                index++;
            }

            sb.AppendLine("        return properties;");
        }

        sb.AppendLine("    }");
    }

    private static void EmitConstructorMethods(StringBuilder sb, TypeModel type, FastJsonOptionsModel options)
    {
        sb.AppendLine($"    private static JsonParameterInfoValues[] Create_{type.ContextPropertyName}_CtorParams()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new JsonParameterInfoValues[{type.ConstructorParameters.Length}]");
        sb.AppendLine("        {");

        foreach (var param in type.ConstructorParameters)
        {
            sb.AppendLine($"            new JsonParameterInfoValues()");
            sb.AppendLine("            {");
            sb.AppendLine($"                Name = \"{param.Name}\",");
            sb.AppendLine($"                ParameterType = typeof({param.TypeFullyQualifiedName}),");
            sb.AppendLine($"                Position = {param.Position},");
            sb.AppendLine($"                HasDefaultValue = {param.HasDefaultValue.ToString().ToLower()},");
            if (param.HasDefaultValue && param.DefaultValueString != null)
            {
                sb.AppendLine($"                DefaultValue = {param.DefaultValueString},");
            }
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    private static {type.FullyQualifiedName} Create_{type.ContextPropertyName}_FromArgs(object[] args)");
        sb.AppendLine("    {");
        sb.Append($"        return new {type.FullyQualifiedName}(");

        var paramList = new System.Collections.Generic.List<string>();
        foreach (var param in type.ConstructorParameters)
        {
            paramList.Add($"({param.TypeFullyQualifiedName})args[{param.Position}]!");
        }
        sb.Append(string.Join(", ", paramList));

        sb.AppendLine(");");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// No longer needed - returns empty string.
    /// </summary>
    public static string EmitWrapper(EquatableArray<TypeModel> types)
    {
        return string.Empty;
    }

    private static string GetNamingPolicyCode(string policy)
    {
        return policy switch
        {
            "CamelCase" => "JsonNamingPolicy.CamelCase",
            "PascalCase" => "null",
            "SnakeCaseLower" => "JsonNamingPolicy.SnakeCaseLower",
            "SnakeCaseUpper" => "JsonNamingPolicy.SnakeCaseUpper",
            "KebabCaseLower" => "JsonNamingPolicy.KebabCaseLower",
            "KebabCaseUpper" => "JsonNamingPolicy.KebabCaseUpper",
            _ => "JsonNamingPolicy.CamelCase"
        };
    }
}
